name: production-cd.yml
on:
  push:
    branches:
      - main

jobs:
  project-deploy:
    runs-on: ubuntu-latest

    env:
      APP_DIR: "/var/www/nextframe-uiux"
      DIST_DIR: "./dist"
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate build
        run: pnpm build
        env:
          VITE_TOSS_CLIENT_KEY: ${{ secrets.VITE_TOSS_CLIENT_KEY }}
          VITE_KAKAO_JAVASCRIPT_KEY: ${{ secrets.VITE_KAKAO_JAVASCRIPT_KEY }}
          VITE_KAKAO_REDIRECT_KEY: ${{ secrets.VITE_KAKAO_REDIRECT_KEY }}
          VITE_BACKEND_SRT_API: ${{ secrets.VITE_BACKEND_SRT_API }}
          VITE_BACKEND_PAYMENT_API: ${{ secrets.VITE_BACKEND_PAYMENT_API }}
          VITE_ENABLE_MSW: ${{ secrets.VITE_ENABLE_MSW }}

      - name: SSH Agent 셋업
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 중간(Bastion) 서버 연결 테스트
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.BASTION_USER}}@${{secrets.BASTION_HOST}} -p ${{ secrets.BASTION_PORT }} "echo \"Bastion 중간 서버 연결 성공\""

      - name: 빌드 파일 애플리케이션 서버로 복사
        run: |
          scp -r -o StrictHostKeyChecking=no \
              -J ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}:${{ secrets.BASTION_PORT }} \
              ${{env.DIST_DIR}} \
              ${{ secrets.DAISY04_USER }}@${{ secrets.DAISY04_HOST }}:${{ env.APP_DIR }}/

      - name: 애플리케이션 서버에 변경 사항 적용
        run: |
          ssh -o StrictHostKeyChecking=no \
              -J ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}:${{ secrets.BASTION_PORT }} \
              ${{ secrets.DAISY04_USER }}@${{ secrets.DAISY04_HOST }}
